using System;
using System.Collections.Generic;
using System.Globalization;
using ARControl.GameData;

namespace ARControl;

/// <summary>
/// Centralized user-facing text. Simplified Chinese is the default; missing translations fall back to English.
/// </summary>
internal static class L
{
    private static readonly Dictionary<LKey, string> English = new()
    {
        [LKey.ManageRetainers] = "Manage retainers",
        [LKey.ConfigWindowTitle] = "ARC",
        [LKey.CommandAlias] = "Alias of /arcontrol",
        [LKey.SyncFailed] = "Unable to synchronize characters with AutoRetainer, plugin might not work properly.",
        [LKey.AssigningVenturePrefix] = " Sending retainer ",
        [LKey.AssigningVentureMiddle] = " to collect ",
        [LKey.AssigningVentureFor] = " for ",
        [LKey.NoTasksPrefix] = " No tasks left for retainer ",
        [LKey.NoTasksMiddle] = ", sending to ",
        [LKey.QuickVenture] = "Quick Venture",
        [LKey.ManagedByArc] = "This retainer is managed by ARC.",
        [LKey.CharacterGroupValue] = "Character Group: {0}",
        [LKey.NoCharacterToDebug] = "No character to debug.",
        [LKey.RetainerNotFoundNamed] = "Could not find retainer {0}.",
        [LKey.RetainerNotFound] = "Could not find retainer.",
        [LKey.NextVentureQuick] = "Next venture for {0} is Quick Venture.",
        [LKey.NextVentureItem] = "Next venture for {0} is {1}.",
        [LKey.NextVentureNone] = "Next venture for {0} is (none).",
        [LKey.DuplicateIgnored] = "This entry is a duplicate and will be ignored.",
        [LKey.CollectOncePreview] = "Items on this list will be collected once.",
        [LKey.KeepStockedPreview] = "Items on this list will be kept in stock on each character.",
        [LKey.AddListToGroup] = "Add Venture List to this Group",
        [LKey.GroupsTab] = "Groups###TabGroups",
        [LKey.Save] = "Save",
        [LKey.Delete] = "Delete",
        [LKey.RemoveCharactersBeforeGroupDelete] = "Remove the {0} character(s) from this group before deleting it.",
        [LKey.NoCharacters] = "no characters",
        [LKey.OneCharacter] = "1 character",
        [LKey.ManyCharacters] = "{0} characters",
        [LKey.VentureLists] = "Venture Lists",
        [LKey.Characters] = "Characters",
        [LKey.CharactersInGroup] = "Characters in this group:",
        [LKey.AddGroup] = "Add Group",
        [LKey.GroupNameHint] = "Group Name...",
        [LKey.CollectOnce] = "Collect Once",
        [LKey.KeepInStock] = "Keep in Stock",
        [LKey.PriorityInOrder] = "Collect in order of the list",
        [LKey.PriorityBalanced] = "Collect item with lowest inventory first",
        [LKey.VentureListsTab] = "Venture Lists###TabVentureLists",
        [LKey.RemoveListBeforeDelete] = "Remove this list from the {0} character(s) and {1} group(s) using it before deleting it.",
        [LKey.DiscardHelperWarning] = "This item will be automatically discarded by 'Discard Helper'.",
        [LKey.CrystalTransferWarning] = "You are responsible for manually moving shards or crystals to your retainers - ARC won't do that for you.\nIf you don't, this may lead to wasted ventures.",
        [LKey.CrystalCapWarning] = "You can never have this many of a shard or crystal in your inventory.",
        [LKey.AddVentureList] = "Add Venture List",
        [LKey.ListNameHint] = "List Name...",
        [LKey.CheckRetainerInventory] = "Check Retainer Inventory for items (requires AllaganTools)",
        [LKey.AddVentureHint] = "Add Venture...",
        [LKey.FilterHint] = "Filter...",
        [LKey.ImportClipboard] = "Import from Clipboard",
        [LKey.TeamcraftImportHelp] = "Supports importing a list in a Teamcraft-compatible format.",
        [LKey.ImportPreview] = "Clicking this button now would add the following items:",
        [LKey.ForExample] = "For example:",
        [LKey.ExampleCobaltOre] = "2000x Cobalt Ore",
        [LKey.ExampleGoldOre] = "1000x Gold Ore",
        [LKey.RemoveFinished] = "Remove all finished items",
        [LKey.RetainersTab] = "Retainers###TabRetainers",
        [LKey.NoGroupManual] = "No Group (manually assign lists)",
        [LKey.CharacterGroup] = "Character Group",
        [LKey.RetainersParticipate] = "Retainers will participate in the following lists:",
        [LKey.None] = "(None)",
        [LKey.Retainers] = "Retainers",
        [LKey.InventoryTab] = "Inventory###TabInventory",
        [LKey.Refresh] = "Refresh",
        [LKey.LastUpdate] = "Last Update: {0:t}",
        [LKey.NoInventoryItems] = "No items in inventory. Do you have AllaganTools installed?",
        [LKey.EmptyList] = "This list is empty.",
        [LKey.InInventory] = "In Inventory",
        [LKey.LockedItemsTab] = "Locked Items###TabLockedItems",
        [LKey.GroupByCharacter] = "Group by character",
        [LKey.OnlyMissing] = "Only show missing items",
        [LKey.MiscTab] = "Misc###TabMisc",
        [LKey.VentureSettings] = "Venture Settings",
        [LKey.MinimumVentures] = "Minimum Ventures needed to assign retainers",
        [LKey.MinimumVenturesHelp] = "If you have less than {0} ventures, retainers will only be sent out for Quick Ventures (instead of picking the next item from the Venture List).",
        [LKey.UiSettings] = "User Interface Settings",
        [LKey.ShowAssignmentChat] = "Show chat message when assigning a venture to a retainer",
        [LKey.ShowListPreview] = "Show Venture List preview in Groups/Retainer tabs",
        [LKey.CategoryMiner] = "MIN",
        [LKey.CategoryBotanist] = "BTN",
        [LKey.CategoryFisher] = "FSH",
        [LKey.CategoryCombat] = "DoWM",
        [LKey.SentenceEnd] = ".",
    };

    private static readonly Dictionary<LKey, string> SimplifiedChinese = new()
    {
        [LKey.ManageRetainers] = "管理雇员探险",
        [LKey.ConfigWindowTitle] = "ARC 设置",
        [LKey.CommandAlias] = "/arcontrol 的别名",
        [LKey.SyncFailed] = "无法与 AutoRetainer 同步角色信息，插件可能无法正常工作。",
        [LKey.AssigningVenturePrefix] = " 正在派遣雇员 ",
        [LKey.AssigningVentureMiddle] = " 采集 ",
        [LKey.AssigningVentureFor] = "，所属探险列表：",
        [LKey.NoTasksPrefix] = " 雇员 ",
        [LKey.NoTasksMiddle] = " 已无待办任务，将改为执行",
        [LKey.QuickVenture] = "自由探索委托",
        [LKey.ManagedByArc] = "此雇员由 ARC 管理。",
        [LKey.CharacterGroupValue] = "角色分组：{0}",
        [LKey.NoCharacterToDebug] = "没有可供调试的角色。",
        [LKey.RetainerNotFoundNamed] = "找不到雇员 {0}。",
        [LKey.RetainerNotFound] = "找不到雇员。",
        [LKey.NextVentureQuick] = "雇员 {0} 的下一项委托是自由探索委托。",
        [LKey.NextVentureItem] = "雇员 {0} 的下一项委托是{1}。",
        [LKey.NextVentureNone] = "雇员 {0} 没有下一项委托。",
        [LKey.DuplicateIgnored] = "此项与前面的设置重复，将被忽略。",
        [LKey.CollectOncePreview] = "此列表中的物品只会采集一次。",
        [LKey.KeepStockedPreview] = "每个角色都会将此列表中的物品维持在设定库存。",
        [LKey.AddListToGroup] = "向此分组添加探险列表",
        [LKey.GroupsTab] = "分组###TabGroups",
        [LKey.Save] = "保存",
        [LKey.Delete] = "删除",
        [LKey.RemoveCharactersBeforeGroupDelete] = "请先将此分组中的 {0} 个角色移出，再删除该分组。",
        [LKey.NoCharacters] = "无角色",
        [LKey.OneCharacter] = "1 个角色",
        [LKey.ManyCharacters] = "{0} 个角色",
        [LKey.VentureLists] = "探险列表",
        [LKey.Characters] = "角色",
        [LKey.CharactersInGroup] = "此分组中的角色：",
        [LKey.AddGroup] = "添加分组",
        [LKey.GroupNameHint] = "分组名称……",
        [LKey.CollectOnce] = "仅采集一次",
        [LKey.KeepInStock] = "维持库存",
        [LKey.PriorityInOrder] = "按列表顺序采集",
        [LKey.PriorityBalanced] = "优先采集当前库存最少的物品",
        [LKey.VentureListsTab] = "探险列表###TabVentureLists",
        [LKey.RemoveListBeforeDelete] = "请先从正在使用此列表的 {0} 个角色和 {1} 个分组中移除该列表，再将其删除。",
        [LKey.DiscardHelperWarning] = "此物品会被“Discard Helper”自动丢弃。",
        [LKey.CrystalTransferWarning] = "碎晶和水晶需要由你手动转移给雇员，ARC 不会代为转移。\n若未及时转移，可能会浪费探险币。",
        [LKey.CrystalCapWarning] = "背包无法容纳这么多碎晶或水晶。",
        [LKey.AddVentureList] = "添加探险列表",
        [LKey.ListNameHint] = "列表名称……",
        [LKey.CheckRetainerInventory] = "将雇员所持物品计入库存（需要 AllaganTools）",
        [LKey.AddVentureHint] = "添加探险委托……",
        [LKey.FilterHint] = "筛选……",
        [LKey.ImportClipboard] = "从剪贴板导入",
        [LKey.TeamcraftImportHelp] = "支持导入 Teamcraft 兼容格式的列表。",
        [LKey.ImportPreview] = "现在点击此按钮将添加以下物品：",
        [LKey.ForExample] = "例如：",
        [LKey.ExampleCobaltOre] = "2000x 钴铁矿",
        [LKey.ExampleGoldOre] = "1000x 金矿",
        [LKey.RemoveFinished] = "移除所有已完成物品",
        [LKey.RetainersTab] = "雇员###TabRetainers",
        [LKey.NoGroupManual] = "不加入分组（手动分配列表）",
        [LKey.CharacterGroup] = "角色分组",
        [LKey.RetainersParticipate] = "雇员将执行以下探险列表：",
        [LKey.None] = "（无）",
        [LKey.Retainers] = "雇员",
        [LKey.InventoryTab] = "库存###TabInventory",
        [LKey.Refresh] = "刷新",
        [LKey.LastUpdate] = "最后更新：{0:t}",
        [LKey.NoInventoryItems] = "未找到库存物品。是否已安装 AllaganTools？",
        [LKey.EmptyList] = "此列表为空。",
        [LKey.InInventory] = "角色背包",
        [LKey.LockedItemsTab] = "未解锁物品###TabLockedItems",
        [LKey.GroupByCharacter] = "按角色分组",
        [LKey.OnlyMissing] = "仅显示尚未解锁的物品",
        [LKey.MiscTab] = "其他###TabMisc",
        [LKey.VentureSettings] = "探险设置",
        [LKey.MinimumVentures] = "派遣雇员所需的最低探险币数量",
        [LKey.MinimumVenturesHelp] = "探险币少于 {0} 枚时，雇员只会执行自由探索委托，不会从探险列表中选择下一项物品。",
        [LKey.UiSettings] = "界面设置",
        [LKey.ShowAssignmentChat] = "为雇员分配探险委托时在聊天栏显示消息",
        [LKey.ShowListPreview] = "在“分组”和“雇员”页签中显示探险列表预览",
        [LKey.CategoryMiner] = "采矿工",
        [LKey.CategoryBotanist] = "园艺工",
        [LKey.CategoryFisher] = "捕鱼人",
        [LKey.CategoryCombat] = "战斗职业",
        [LKey.SentenceEnd] = "。",
    };

    public static string Text(LKey key, params object?[] args)
    {
        string value = SimplifiedChinese.TryGetValue(key, out var translated)
            ? translated
            : English[key];
        return args.Length == 0 ? value : string.Format(CultureInfo.CurrentCulture, value, args);
    }

    public static string VentureCategory(EVentureCategoryType category) => category switch
    {
        EVentureCategoryType.MIN => Text(LKey.CategoryMiner),
        EVentureCategoryType.BTN => Text(LKey.CategoryBotanist),
        EVentureCategoryType.FSH => Text(LKey.CategoryFisher),
        EVentureCategoryType.DoWM => Text(LKey.CategoryCombat),
        _ => string.Empty,
    };
}

internal enum LKey
{
    ManageRetainers,
    ConfigWindowTitle,
    CommandAlias,
    SyncFailed,
    AssigningVenturePrefix,
    AssigningVentureMiddle,
    AssigningVentureFor,
    NoTasksPrefix,
    NoTasksMiddle,
    QuickVenture,
    ManagedByArc,
    CharacterGroupValue,
    NoCharacterToDebug,
    RetainerNotFoundNamed,
    RetainerNotFound,
    NextVentureQuick,
    NextVentureItem,
    NextVentureNone,
    DuplicateIgnored,
    CollectOncePreview,
    KeepStockedPreview,
    AddListToGroup,
    GroupsTab,
    Save,
    Delete,
    RemoveCharactersBeforeGroupDelete,
    NoCharacters,
    OneCharacter,
    ManyCharacters,
    VentureLists,
    Characters,
    CharactersInGroup,
    AddGroup,
    GroupNameHint,
    CollectOnce,
    KeepInStock,
    PriorityInOrder,
    PriorityBalanced,
    VentureListsTab,
    RemoveListBeforeDelete,
    DiscardHelperWarning,
    CrystalTransferWarning,
    CrystalCapWarning,
    AddVentureList,
    ListNameHint,
    CheckRetainerInventory,
    AddVentureHint,
    FilterHint,
    ImportClipboard,
    TeamcraftImportHelp,
    ImportPreview,
    ForExample,
    ExampleCobaltOre,
    ExampleGoldOre,
    RemoveFinished,
    RetainersTab,
    NoGroupManual,
    CharacterGroup,
    RetainersParticipate,
    None,
    Retainers,
    InventoryTab,
    Refresh,
    LastUpdate,
    NoInventoryItems,
    EmptyList,
    InInventory,
    LockedItemsTab,
    GroupByCharacter,
    OnlyMissing,
    MiscTab,
    VentureSettings,
    MinimumVentures,
    MinimumVenturesHelp,
    UiSettings,
    ShowAssignmentChat,
    ShowListPreview,
    CategoryMiner,
    CategoryBotanist,
    CategoryFisher,
    CategoryCombat,
    SentenceEnd,
}
